/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/categorias` | `/categorias`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/editar` | `/editar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/logout` | `/logout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/modificarCategoria` | `/modificarCategoria`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/modificarProveedor` | `/modificarProveedor`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/proveedores` | `/proveedores`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/registrarCategoria` | `/registrarCategoria`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/registrarProveedor` | `/registrarProveedor`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/categorias` | `/categorias`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/editar` | `/editar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/logout` | `/logout`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/modificarCategoria` | `/modificarCategoria`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/modificarProveedor` | `/modificarProveedor`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/proveedores` | `/proveedores`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/registrarCategoria` | `/registrarCategoria`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/registrarProveedor` | `/registrarProveedor`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/categorias${`?${string}` | `#${string}` | ''}` | `/categorias${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/editar${`?${string}` | `#${string}` | ''}` | `/editar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/logout${`?${string}` | `#${string}` | ''}` | `/logout${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/modificarCategoria${`?${string}` | `#${string}` | ''}` | `/modificarCategoria${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/modificarProveedor${`?${string}` | `#${string}` | ''}` | `/modificarProveedor${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/proveedores${`?${string}` | `#${string}` | ''}` | `/proveedores${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/registrarCategoria${`?${string}` | `#${string}` | ''}` | `/registrarCategoria${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/registrarProveedor${`?${string}` | `#${string}` | ''}` | `/registrarProveedor${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/categorias` | `/categorias`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/editar` | `/editar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/logout` | `/logout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/modificarCategoria` | `/modificarCategoria`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/modificarProveedor` | `/modificarProveedor`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/proveedores` | `/proveedores`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/registrarCategoria` | `/registrarCategoria`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/registrarProveedor` | `/registrarProveedor`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
