# Yaml de categorias
openapi: 3.0.0
info: 
  title: API TechCraft Dynamics - Categorías
  version: 1.0.0
tags:
  - name: Categorías 📚
    description: Endpoint para gestionar las categorías

paths:

# ---------------------------------------------------------------------------------
# Mostramos todas las categorías 
# No es necesario agregar los campos porque solo estamos mostrando los que ya existen
  /api/categorias:
    get:
      summary: Lista de todas las categorías
      tags: [Categorías 📚]

      # Descripcion de los errores
      responses: 
        "200":
          description: Lista de categorías
          content:
            application/json:
              schema:
                type: object
                properties:
                  Nombre_categoria:
                    type: string
                    example: Comida perros 
                  Imagen_categoria:
                    type: string
                    format: binary
                    example: comida_perros.jpg
                  Descripcion:
                    type: string
                    example: Se tiene los diferentes sabores y marcas de la comida para perros
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Error interno del servidor

# ---------------------------------------------------------------------------------
# Creamos una categoría nueva
    post: 
      summary: Crear categoría nueva
      tags: [Categorías 📚]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                Nombre_categoria:
                  type: string
                Imagen_categoria:
                  type: string
                  format: binary
                  example: Imagen_categoria.jpg
                Descripcion:
                  type: string

      # Descripcion de los errores
      responses:
        "200":
          description: Categoría creada exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  Nombre_categoria:
                    type: string
                    example: Comida perros 
                  Imagen_categoria:
                    type: string
                    format: binary
                    example: comida_perros.jpg
                  Descripcion:
                    type: string
                    example: Se tiene los diferentes sabores y marcas de la comida para perros
        "400":
          description: Error al crear la categoría
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Error al crear la categoria
        "500":
          description: Error del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Error interno del servidor

# ---------------------------------------------------------------------------------
# Mostramos la categoría buscado por su ID
  /api/categorias/{id}:
    get:
      summary: Obtiene una unica categoría por su ID 
      tags: [Categorías 📚]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Ingrese el ID de la categoría exacta para visualizar

      # Descripcion de los errores
      responses:
        "200":
          description: Categoría encontrada exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  Nombre_categoria:
                    type: string
                    example: Comida perros 
                  Imagen_categoria:
                    type: string
                    format: binary
                    example: comida_perros.jpg
                  Descripcion:
                    type: string
                    example: Se tiene los diferentes sabores y marcas de la comida para perros
        "404":
          description: Categoría no encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: No se pudo encontrar la categoria solicitada
        "500":
          description: Error del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Error interno del servidor

# ---------------------------------------------------------------------------------
# Actualizamos la categoría buscado por su ID
    put:
      summary: Actualizar una categoría existente
      tags: [Categorías 📚]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Ingrese el ID de la categoría que quiere actualizar 
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                Nombre_categoria:
                  type: string
                Imagen_categoria:
                  type: string
                  format: binary
                  example: Imagen_categoria.jpg
                Descripcion:
                  type: string
                activo:
                  type: boolean

      # Descripcion de los errores
      responses:
        "200":
          description: Categoría actualizada exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  Nombre_categoria:
                    type: string
                    example: Comida perros 
                  Imagen_categoria:
                    type: string
                    format: binary
                    example: comida_perros.jpg
                  Descripcion:
                    type: string
                    example: Se tiene los diferentes sabores y marcas de la comida para perros
        "400":
          description: Error no se pudo actualizar la categoría
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Error no se pudo actualizar la categoría
        "404":
          description: No se pudo encontrar la categoría requerida
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: No se pudo encontrar la categoría requerida
        "500":
          description: Error del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Error interno del servidor

# ---------------------------------------------------------------------------------
# Eliminamos la categoría buscada por su ID 
  /api/categorias/delete/{id}:
    delete:
      summary: Eliminar categoría existente
      tags: [Categorías 📚]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Ingrese el ID de la categoría que quiere eliminar 

      # Descripcion de los errores 
      responses:
        "200":
          description: Categoría eliminada correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  Nombre_categoria:
                    type: string
                    example: Comida perros 
                  Imagen_categoria:
                    type: string
                    format: binary
                    example: comida_perros.jpg
                  Descripcion:
                    type: string
                    example: Se tiene los diferentes sabores y marcas de la comida para perros
        "404": 
          description: No se pudo encontrar la categoría requerida
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    mensaje:
                      type: string
                      example: No se pudo encontrar la categoría requerida
        "500":
          description: Error del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Error interno del servidor