# Yaml de categorias
openapi: 3.0.0
info: 
  title: API TechCraft Dynamics - Categorías
  version: 1.0.0
tags:
  - name: Categorías 📚
    description: Endpoint para gestionar las categorías

paths:
  /api/categorias:
# Mostramos todas las categorías 
# No es necesario agregar los campos porque solo estamos mostrando los que ya existen
    get:
      summary: Lista de todas las categorías
      tags: [Categorías 📚]
      responses: 
        "200":
          description: Lista de categorías
        "500":
          description: No se pudo listar las categorías existentes
    
# Creamos una categoría nueva
    post: 
      summary: Crear categoría nueva
      tags: [Categorías 📚]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                Nombre_categoria:
                  type: string
                Imagen_categoria:
                  type: string
                  format: binary
                Descripcion:
                  type: string
        responses:
          "201":
            description: Categoría creada exitosamente
          "400":
            description: Error al crear la categoría
  
# Mostramos la categoría buscado por su ID
  /api/categorias/{id}:
    get:
      summary: Obtiene una unica categoría por su ID 
      tags: [Categorías 📚]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Ingrese el ID de la categoría exacta para visualizar 
      responses:
        "200":
          description: Categoría encontrada exitosamente
        "404":
          description: No se pudo encontrar la categoria solicitada

# Actualizamos la categoría buscado por su ID
    put:
      summary: Actualizar una categoría existente
      tags: [Categorías 📚]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Ingrese el ID de la categoría que quiere actualizar 
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                Nombre_categoria:
                  type: string
                Imagen_categoria:
                  type: string
                  format: binary
                Descripcion:
                  type: string
                activo:
                  type: boolean
        responses:
          "201":
            description: Categoría actualizada exitosamente
          "400":
            description: Error no se pudo actualizar la categoría
          "404":
            description: No se pudo encontrar la categoría requerida

# Eliminamos la categoría buscada por su ID 
  /api/categorias/delete/{id}:
    delete:
      summary: Eliminar categoría existente
      tags: [Categorías 📚]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Ingrese el ID de la categoría que quiere eliminar 
      responses:
        "200":
          description: Categoría eliminada correctamente
        "404": 
          description: No se pudo encontrar la categoría requerida