# Yaml de usuarios
openapi: 3.0.0
info: 
  title: API TechCraft Dynamics - Perfil
  version: 1.0.0
tags:
  - name: Perfil
    description: Endpoint para gestionar los perfil

paths:
  /api/perfil/{id}:
    get:
      summary: Vista del perfil por su id
      tags: [Perfil]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses: 
        "200":
          description: Perfil del usuario por su id
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  Primer_Nombre:
                    type: string
                  Segundo_Nombre:
                    type: string
                  Primer_Apellido:
                    type: string
                  Segundo_Apellido:
                    type: string
                  Tipo_documento:
                    type: string
                  Numero_documento:
                    type: string
                  Numero_celular:
                    type: string
                  Correo_personal:
                    type: string
                  Correo_empresarial:
                    type: string
                  Rol:
                    type: string
                  imagen:
                    type: string
        "404":
          description: Usuario no encontrado
        "500":
          description: Error interno al buscar datos del usuario
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string


  
    put:
      summary: Actualizar perfil por su id
      tags: [Perfil]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Primer_Nombre:
                  type: string
                Segundo_Nombre:
                  type: string
                Primer_Apellido:
                  type: string
                Segundo_Apellido:
                  type: string
                Tipo_documento:
                  type: string
                Numero_documento:
                  type: string
                Numero_celular:
                  type: string
                Correo_personal:
                  type: string
                Correo_empresarial:
                  type: string
                Rol:
                  type: string
                imagen:
                  type: string
      responses:
        "200":
          description: Perfil actualizado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: Error de validación (datos faltantes o inválidos)
        "404":
          description: Usuario no encontrado
        "500":
          description: Error interno al actualizar el perfil
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
