# # Yaml de gramaje 
# openapi: 3.0.0
# info: 
#   title: API TechCraft Dynamics - Productos
#   version: 1.0.0
# tags:
#   - name: Productos
#     description: Endpoint para gestionar los productos (Paquete y Gramaje)

# paths:
#   /api/Productos/gramaje:
#   # Listar productos gramaje
#     get:
#       summary: Lista de todos los productos de tipo gramaje
#       tags: [Productos]
#       responses: 
#         "200":
#           description: Lista de productos gramaje
#           content:
#             application/json:
#               schema:
#                 type: array
#                 items:
#                   type: object
#                   properties:
#                     id:
#                       type: integer
#                     imagen_producto:
#                       type: string
#                       format: uri
#                     nombre_producto:
#                       type: string
#                     Kilogramos:
#                       type: integer
#                     precio_kilogramo:
#                       type: integer
#                     Libras: 
#                       type: integer
#                     precio_libras:
#                       type: integer
#                     descripcion:
#                       type: string
#                     id_subcategoria:
#                       type: integer
#                     id_productospaquete:
#                       type: integer
#                     id_proveedor:
#                       type: integer
#                     tipo_producto:
#                       type: string
#                       enum: [gramaje]
#                     activo:
#                       type: boolean
#         "500":
#           description: Error interno al listar productos
#           content:
#             application/json:
#               schema:
#                 type: object
#                 properties:
#                   error:
#                     type: string

#   # Crear un nuevo producto gramaje
#     post: 
#       summary: Crea un nuevo producto de tipo gramaje
#       tags: [Productos]
#       requestBody:
#         required: true
#         content:
#           multipart/form-data:
#             schema:
#               type: object
#               properties:
#                 id:
#                   type: integer
#                 imagen_producto:
#                   type: string
#                   format: binary
#                 nombre_producto:
#                   type: string
#                 Kilogramos:
#                   type: integer
#                 precio_kilogramo:
#                   type: integer
#                 Libras: 
#                   type: integer
#                 precio_libras:
#                   type: integer
#                 descripcion:
#                   type: string
#                 id_subcategoria:
#                   type: integer
#                 id_productospaquete:
#                   type: integer
#                 id_proveedor:
#                   type: integer
#                 tipo_producto:
#                   type: string
#                   enum: [gramaje]
#                 activo:
#                   type: boolean
#         responses:
#           "201":
#             description: Producto creado exitosamente
#           "400":
#             description: Error al crear el producto

#   # Actualizar el producto (gramaje) por su ID
#   /api/Productos/gramaje/{id}:
#     put:
#       summary: Actualiza un producto de tipo gramaje por su ID
#       tags: [Productos]
#       parameters:
#         - in: path
#           name: id
#           required: true
#           schema:
#             type: integer
#           description: ID del producto
#       requestBody:
#         required: true
#         content:
#           multipart/form-data:
#             schema:
#               type: object
#               properties:
#                 id:
#                   type: integer
#                 imagen_producto:
#                   type: string
#                   format: binary
#                 nombre_producto:
#                   type: string
#                 Kilogramos:
#                   type: integer
#                 precio_kilogramo:
#                   type: integer
#                 Libras: 
#                   type: integer
#                 precio_libras:
#                   type: integer
#                 descripcion:
#                   type: string
#                 id_subcategoria:
#                   type: integer
#                 id_productospaquete:
#                   type: integer
#                 id_proveedor:
#                   type: integer
#                 tipo_producto:
#                   type: string
#                   enum: [gramaje]
#                 activo:
#                   type: boolean
#         responses:
#           "201":
#             description: Producto actualizado exitosamente
#           "400":
#             description: Error al encontrar el producto
    
#   # Eliminar el producto
#     delete:
#       summary: Elimina un producto de tipo gramaje por su ID 
#       tags: [Productos]
#       parameters:
#         - in: path
#           name: id
#           required: true
#           schema:
#             type: integer
#           description: ID del producto
#       responses:
#         "200":
#           description: Producto eliminado correctamente
#         "404": 
#           description: Producto no encontrado

#   # Yamal de paquete
#   /api/Productos/paquete:
#     # Listar productos de paquetes
#     get:
#       summary: Lista de todos los productos de tipo paquete
#       tags: [Productos]
#       responses: 
#         "200":
#           description: Lista de productos paquete
#           content:
#             application/json:
#               schema:
#                 type: array
#                 items:
#                   type: object
#                   properties:
#                     id:
#                       type: integer
#                     imagen_producto:
#                       type: string
#                       format: uri
#                     nombre_producto:
#                       type: string
#                     precio:
#                       type: integer
#                     descripcion:
#                       type: string
#                     codigo_de_barras:
#                       type: string
#                     stock:
#                       type: integer
#                     id_subcategoria:
#                       type: integer
#                     id_proveedor:
#                       type: integer
#                     tipo_producto:
#                       type: string
#                       enum: [paquete]
#                     activo:
#                       type: boolean
#         "500":
#           description: Error interno al listar productos
#           content:
#             application/json:
#               schema:
#                 type: object
#                 properties:
#                   error:
#                     type: string

#   # Crear producto (paquete) nuevo
#     post: 
#       summary: Crea un nuevo producto de tipo paquete
#       tags: [Productos]
#       requestBody:
#         required: true
#         content:
#           multipart/form-data:
#             schema:
#               type: object
#               properties:
#                 id:
#                   type: integer
#                 imagen_producto:
#                   type: string
#                   format: binary
#                 nombre_producto:
#                   type: string
#                 precio:
#                   type: integer
#                 descripcion:
#                   type: string
#                 codigo_de_barras:
#                   type: string
#                 stock:
#                   type: integer
#                 id_subcategoria:
#                   type: integer
#                 id_proveedor:
#                   type: integer
#                 tipo_producto:
#                   type: string
#                   enum: [paquete]
#                 activo:
#                   type: boolean
#         responses:
#           "201":
#             description: Producto creado exitosamente
#           "400":
#             description: Error al crear el producto

#   /api/Productos/paquete/{id}:
#   # Actualizar el producto por su ID
#     put:
#       summary: Actualiza un producto de tipo paquete por su ID
#       tags: [Productos]
#       parameters:
#         - in: path
#           name: id
#           required: true
#           schema:
#             type: integer
#           description: ID del producto
#       requestBody:
#         required: true
#         content:
#           multipart/form-data:
#             schema:
#               type: object
#               properties:
#                 id:
#                   type: integer
#                 imagen_producto:
#                   type: string
#                   format: binary
#                 nombre_producto:
#                   type: string
#                 precio:
#                   type: integer
#                 descripcion:
#                   type: string
#                 codigo_de_barras:
#                   type: string
#                 stock:
#                   type: integer
#                 id_subcategoria:
#                   type: integer
#                 id_proveedor:
#                   type: integer
#                 tipo_producto:
#                   type: string
#                   enum: [paquete]
#                 activo:
#                   type: boolean
#         responses:
#           "201":
#             description: Producto actualizado exitosamente
#           "400":
#             description: Error al encontrar el producto

#     # Eliminar el producto
#     delete:
#       summary: Elimina un producto de tipo paquete por su ID 
#       tags: [Productos]
#       parameters:
#         - in: path
#           name: id
#           required: true
#           schema:
#             type: integer
#           description: ID del producto
#       responses:
#         "200":
#           description: Producto eliminado correctamente
#         "404": 
#           description: Producto no encontrado