# Yaml de Usuarios 
openapi: 3.0.0
info: 
  title: API TechCraft Dynamics - Usuarios
  version: 1.0.0
tags:
  - name:  Usuarios 👤
    description: Endpoint para gestionar a los usuarios

paths:
# Mostramos la lista de los usuarios
  /api/usuarios:
    get:
      summary: Lista de todos los usuarios
      tags: [Usuarios 👤]
      responses: 
        "200":
          description: Lista de los usuarios
        "500":
          description: No se pudo listar a los usuarios existentes

# Creamos a un usuario nuevo
    post: 
      summary: Crear usuario nuevo
      tags: [Usuarios 👤]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                Primer_Nombre:
                  type: string
                Segundo_Nombre:
                  type: string
                Primer_Apellido:
                  type: string
                Segundo_Apellido:
                  type: string
                Tipo_documento:
                  type: string
                Numero_documento:
                  type: string
                Numero_celular:
                  type: string
                Correo_personal:
                  type: string
                Correo_empresarial:
                  type: string
                id_Rol:
                  type: integer
                Contrasena: 
                  type: string
      responses:
        "201":
          description: Usuario creado exitosamente
        "400":
          description: Error al crear un usuario nuevo

# Mostramos a un unico usuarios buscandolo por su ID
  /api/usuarios/{id}:
    get: 
      summary: Obtiene un unico usuario por su ID
      tags: [Usuarios 👤]
      parameters: 
        - in: path
          name: id 
          required: true
          schema: 
            type: integer
          description: Ingrese el ID del usuario exacto para visualizar
      responses:
        "200":
          description: Usuario encontrado exitosamente
        "404": 
          description: No se pudo encontrar al usuario requerido

# Actualizamos los datos del usuario buscado por su ID
    put:
      summary: Actualizar un usuario existente 
      tags: [Usuarios 👤]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Ingrese el ID del usuario que quiere actualizar
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                Primer_Nombre:
                  type: string
                Segundo_Nombre:
                  type: string
                Primer_Apellido:
                  type: string
                Segundo_Apellido:
                  type: string
                Tipo_documento:
                  type: string
                Numero_documento:
                  type: string
                Numero_celular:
                  type: string
                Correo_personal:
                  type: string
                Correo_empresarial:
                  type: string
                id_Rol:
                  type: integer
                Contrasena: 
                  type: string
                activo:
                  type: boolean
      responses:
        "201":
          description: Usuario actualizado exitosamente
        "400":
          description: Error no se pudo actualizar al usuario
        "404":
          description: No se pudo encontrar al usuario requerido

# Eliminamos al usuario buscado por su ID
  /api/usuarios/delete/{id}:
    delete:
      summary: Eliminar usuario existente
      tags: [Usuarios 👤]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Ingrese el ID del usuario que quiere eliminar 
      responses:
        "200":
          description: Usuario eliminado correctamente
        "404": 
          description: No se pudo encontrar al usuario requerido
