# Yaml de usuarios
openapi: 3.0.0
info: 
  title: API TechCraft Dynamics - Ventas
  version: 1.0.0
tags:
  - name: Ventas
    description: Endpoint para gestionar los Ventas

paths:
  /api/ventas:
  # Listar ventas
    get:
      summary: Lista de todas las ventas
      tags: [Ventas]
      responses: 
        "200":
          description: Lista de las ventas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    id_productosGramaje:
                      type: integer
                    id_productosProducto:
                      type: integer
                    cantidad: 
                      type: integer
                    valor_unitario:
                      type: float
                    descuento:
                      type: float
                    subtotal:
                      type: float
                    metodo_pago:
                      type: string
                    info_pago:
                      type: string
                    detalle_venta:
                      type: string
                    fecha:
                      type: date
        "500":
          description: Error interno al listar ventas
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    # Crear una venta nueva
    post: 
      summary: Crear una venta nueva
      tags: [Ventas]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                id:
                  type: integer
                id_productosGramaje:
                  type: integer
                id_productosProducto:
                  type: integer
                cantidad: 
                  type: integer
                valor_unitario:
                  type: float
                descuento:
                  type: float
                subtotal:
                  type: float
                metodo_pago:
                  type: string
                info_pago:
                  type: string
                detalle_venta:
                  type: string
                fecha:
                  type: date
        responses:
          "201":
            description: Venta creada exitosamente
          "400":
            description: Error al crear una venta

  # Eliminar el proveedor
    delete:
      summary: Elimina venta por su ID 
      tags: [Ventas]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID del ventas
      responses:
        "200":
          description: Venta eliminada correctamente
        "404": 
          description: Venta no encontrado